config/routes.rb
Rails.application.routes.draw do
  resources :pedidos do
  	resources :pedido_produtos
  end
  resources :receitas
  resources :despesas
  resources :fornecedores
  resources :produtos
  resources :clientes
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "home#index"
end

app/models/produto.rb
class Produto < ApplicationRecord
  validates :nome, presence: true
end

app/controllers/produtos_controller.rb
class ProdutosController < ApplicationController
  before_action :set_produto, only: [:show, :edit, :update, :destroy]

  # GET /produtos
  # GET /produtos.json
  def index
    @produtos = Produto.all

    if params[:nome].present?
      @produtos = @produtos.where("lower(nome) ilike '%#{URI::encode(params[:nome])}%' ")
    end

    options = {page: params[:page] || 1, per_page: 10}
    @produtos = @produtos.paginate(options)
  end

  # GET /produtos/1
  # GET /produtos/1.json
  def show
  end

  # GET /produtos/new
  def new
    @produto = Produto.new
  end

  # GET /produtos/1/edit
  def edit
  end

  # POST /produtos
  # POST /produtos.json
  def create
    @produto = Produto.new(produto_params)

    respond_to do |format|
      if @produto.save
        format.html { redirect_to @produto, notice: 'Produto was successfully created.' }
        format.json { render :show, status: :created, location: @produto }
      else
        format.html { render :new }
        format.json { render json: @produto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /produtos/1
  # PATCH/PUT /produtos/1.json
  def update
    respond_to do |format|
      if @produto.update(produto_params)
        format.html { redirect_to @produto, notice: 'Produto was successfully updated.' }
        format.json { render :show, status: :ok, location: @produto }
      else
        format.html { render :edit }
        format.json { render json: @produto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /produtos/1
  # DELETE /produtos/1.json
  def destroy
    @produto.destroy
    respond_to do |format|
      format.html { redirect_to produtos_url, notice: 'Produto was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_produto
      @produto = Produto.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def produto_params
      params.require(:produto).permit(:nome, :descricao, :quantidade, :vencimento, :preco_compra, :preco_venda)
    end
end

app/helpers/produtos_helper.rb
module ProdutosHelper
end

app/views/produtos/_form.html.erb
<%= form_for(@produto, html: { class: "form-horizontal", role: "form" }) do |f| %>
  <% if @produto.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4>Confira os campos abaixo:</h4>

      <ul>
      <% @produto.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :nome, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :nome, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :descricao, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_area :descricao, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :quantidade, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.number_field :quantidade, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :vencimento, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.datetime_field :vencimento, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :preco_compra, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :preco_compra, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :preco_venda, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :preco_venda, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit "Salvar", class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/produtos/edit.html.erb
<div class="page-header">
  <%= link_to produtos_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Voltar
  <% end %>
  <%= link_to @produto, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Mostrar
  <% end %>
  <h1>Editando produto</h1>
</div>

<%= render 'form' %>

app/views/produtos/index.html.erb
<div class="page-header">
  <%= link_to new_produto_path, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    Novo
  <% end %>
  <h1>Lista</h1>
</div>

<div style="text-align: right;margin-top:10px">
  <form action="/produtos" method="get">
    <div class="row" style="width:300px;display: inline-block;">
      <div style="float: left">
        <input type="text" name="nome" value="<%= params[:nome] %>" class="form-control" placeholder="Busca ..">
      </div>
      <div style="float: left;margin-left:5px">
        <input type="submit" class="btn btn-primary" value="Buscar"></div>
    </div>
  </form>
</div>
<hr>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
        <th>Nome</th>
        <th>Descricao</th>
        <th>Quantidade</th>
        <th>Vencimento</th>
        <th>Preco compra</th>
        <th>Preco venda</th>
        <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @produtos) do |produto| %>
        <td><%= produto.nome %></td>
        <td><%= produto.descricao %></td>
        <td><%= produto.quantidade %></td>
        <td><%= produto.vencimento %></td>
        <td><%= produto.preco_compra %></td>
        <td><%= produto.preco_venda %></td>
        <td><%= link_to 'Mostrar', produto %></td>
        <td><%= link_to 'Editar', edit_produto_path(produto) %></td>
        <td><%= link_to 'Apagar', produto, method: :delete, data: { confirm: 'Confirma?' } %></td>
      <% end %>
    </tbody>
  </table>
  <div class="apple_pagination">
    <%= will_paginate @concursos, :container => false %>
  </div>
</div>

app/views/produtos/new.html.erb
<div class="page-header">
  <%= link_to produtos_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Voltar
  <% end %>
  <h1>Novo</h1>
</div>

<%= render 'form' %>

app/views/produtos/show.html.erb
<div class="page-header">
  <%= link_to produtos_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Voltar
  <% end %>
  <%= link_to edit_produto_path(@produto), class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Editar
  <% end %>
  <h1>Mostrar</h1>
</div>

<dl class="dl-horizontal">
  <dt>Nome:</dt>
  <dd><%= @produto.nome %></dd>
  <dt>Descricao:</dt>
  <dd><%= @produto.descricao %></dd>
  <dt>Quantidade:</dt>
  <dd><%= @produto.quantidade %></dd>
  <dt>Vencimento:</dt>
  <dd><%= @produto.vencimento %></dd>
  <dt>Preco compra:</dt>
  <dd><%= @produto.preco_compra %></dd>
  <dt>Preco venda:</dt>
  <dd><%= @produto.preco_venda %></dd>
</dl>